GET http://localhost:3001/facilities

###

POST http://localhost:3001/facility/new
Content-Type: application/json

{
    "name":"Walter's Mart",
    "street": "3232 Some St.",
    "city": "Some city",
    "state": "Some state",
    "zip": 75050
}
###

DELETE http://localhost:3001/todo/delete/

###

GET http://localhost:3001/todo/complete/66994e5c6c666639b5eac8e5