GET http://localhost:3001/facilities

###

POST http://localhost:3001/facility/new
Content-Type: application/json

{
    "name":"Walter's Mart",
    "street": "3232 Some St.",
    "city": "Some city",
    "state": "Some state",
    "zip": 75050
}
###

POST http://localhost:3001/device/new
Content-Type: application/json

{  
     "manufacturer": "Febco",
    "model": "850",
    "size": "1",
    "type": "Double Check",
    "serialNumber": "longserial#######",
    "locationDescription": "next to wm",
    "mapGeo": { "lat": "2323",
  "long":  "2323232" ,}
   
}
###

DELETE http://localhost:3001/todo/delete/

###

GET http://localhost:3001/todo/complete/66994e5c6c666639b5eac8e5